#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-purrrlyr
Version  : 0.0.8
Release  : 2
URL      : https://cran.r-project.org/src/contrib/purrrlyr_0.0.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/purrrlyr_0.0.8.tar.gz
Summary  : Tools at the Intersection of 'purrr' and 'dplyr'
Group    : Development/Tools
License  : GPL-3.0
Requires: R-purrrlyr-lib = %{version}-%{release}
Requires: R-purrrlyr-license = %{version}-%{release}
Requires: R-Rcpp
Requires: R-dplyr
Requires: R-magrittr
Requires: R-purrr
BuildRequires : R-Rcpp
BuildRequires : R-dplyr
BuildRequires : R-magrittr
BuildRequires : R-purrr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
'purrr' that formerly lived in 'purrr'.

%package lib
Summary: lib components for the R-purrrlyr package.
Group: Libraries
Requires: R-purrrlyr-license = %{version}-%{release}

%description lib
lib components for the R-purrrlyr package.


%package license
Summary: license components for the R-purrrlyr package.
Group: Default

%description license
license components for the R-purrrlyr package.


%prep
%setup -q -n purrrlyr

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693259061

%install
export SOURCE_DATE_EPOCH=1693259061
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-purrrlyr
cp %{_builddir}/purrrlyr/LICENSE %{buildroot}/usr/share/package-licenses/R-purrrlyr/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/purrrlyr/DESCRIPTION
/usr/lib64/R/library/purrrlyr/INDEX
/usr/lib64/R/library/purrrlyr/LICENSE
/usr/lib64/R/library/purrrlyr/Meta/Rd.rds
/usr/lib64/R/library/purrrlyr/Meta/features.rds
/usr/lib64/R/library/purrrlyr/Meta/hsearch.rds
/usr/lib64/R/library/purrrlyr/Meta/links.rds
/usr/lib64/R/library/purrrlyr/Meta/nsInfo.rds
/usr/lib64/R/library/purrrlyr/Meta/package.rds
/usr/lib64/R/library/purrrlyr/NAMESPACE
/usr/lib64/R/library/purrrlyr/NEWS.md
/usr/lib64/R/library/purrrlyr/R/purrrlyr
/usr/lib64/R/library/purrrlyr/R/purrrlyr.rdb
/usr/lib64/R/library/purrrlyr/R/purrrlyr.rdx
/usr/lib64/R/library/purrrlyr/help/AnIndex
/usr/lib64/R/library/purrrlyr/help/aliases.rds
/usr/lib64/R/library/purrrlyr/help/paths.rds
/usr/lib64/R/library/purrrlyr/help/purrrlyr.rdb
/usr/lib64/R/library/purrrlyr/help/purrrlyr.rdx
/usr/lib64/R/library/purrrlyr/html/00Index.html
/usr/lib64/R/library/purrrlyr/html/R.css
/usr/lib64/R/library/purrrlyr/tests/testthat.R
/usr/lib64/R/library/purrrlyr/tests/testthat/helper-rows.R
/usr/lib64/R/library/purrrlyr/tests/testthat/test-dmap.R
/usr/lib64/R/library/purrrlyr/tests/testthat/test-rows.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/purrrlyr/libs/purrrlyr.so
/usr/lib64/R/library/purrrlyr/libs/purrrlyr.so.avx2
/usr/lib64/R/library/purrrlyr/libs/purrrlyr.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-purrrlyr/8624bcdae55baeef00cd11d5dfcfa60f68710a02
